# Generated by Django 5.2 on 2026-01-15 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('pricing', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_products', to='product.product'),
        ),
        migrations.AddField(
            model_name='price',
            name='market_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.marketbranch'),
        ),
        migrations.AddField(
            model_name='price',
            name='market_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.marketproduct'),
        ),
        migrations.AddConstraint(
            model_name='marketproduct',
            constraint=models.UniqueConstraint(fields=('market', 'external_product_id'), name='uniq_market_external_product'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['market_product', 'market_branch', '-fetched_at'], name='price_lookup_idx'),
        ),
    ]
